name = "api"
main = "./src/index.js"
compatibility_date = "2023-08-14"
node_compat = true

[[ d1_databases ]]
binding = "DB"
database_name = "basic"
database_id = "2d58c7bb-0334-432c-9e3b-29ce915bb070"

#[[d1_databases]]
#binding = "DB" # i.e. available in your Worker on env.DB
#database_name = "visit"
#database_id = "f16cd155-e4b8-4201-bea2-9dcd8b92a909"

#kv_namespaces = [
#     { binding = "__STATIC_CONTENT", id = "e8f557bc074940c890db5a43609dad58" }
#]

#[site]
#bucket = "./public"

routes = [
	{ pattern = "api.bigbrain-studio.com", custom_domain = true }
]