name = "api"
main = "./src/index.js"
compatibility_date = "2023-08-14"

[[ d1_databases ]]
binding = "DB"
database_name = "basic"
database_id = "2d58c7bb-0334-432c-9e3b-29ce915bb070"

kv_namespaces = [
     { binding = "basic", id = "52477016461c45c0995fbc012d4b1ff4", preview_id = "a1e8e1bc5cbe4d91b100ef64203e1190" }
]
#[site]
#bucket = "./public"