name = "test"
main = "src/worker.ts"
workers_dev = true
account_id = "1d44b4bc080be3fb025f311344f57888"
compatibility_date = "2023-08-14"

[[ d1_databases ]]
binding = "DB"
database_name = "northwind-demo"
database_id = "8a095b42-3932-417d-8995-1ee11b4d6082"

